application: endeleo-website
version: 1 
runtime: python 
api_version: 1

default_expiration: "30d"

handlers: 
- url: /img/(.*) 
  static_files: img/\1 
  upload: img/(.*) 
- url: /css/(.*) 
  static_files: css/\1 
  upload: css/(.*) 
- url: /js/(.*) 
  static_files: js/\1 
  upload: js/(.*) 
- url: /fonts/(.*) 
  static_files: fonts/\1 
  upload: fonts/(.*) 
- url: /(.*\.html) 
  static_files: \1 
  upload: .*.html 
- url: /.* 
  script: main.py